spring.datasource.url=jdbc:postgresql://localhost:5432/cineticket_db

# Credenciais do banco de dados
spring.datasource.username=postgres
spring.datasource.password=postgres

# Configuração do driver do PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Ativa o Flyway para ler os scripts SQL automaticamente
spring.flyway.enabled=true